# Generated by Django 4.1.1 on 2022-09-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOwner', models.IntegerField(unique=True, verbose_name='Owner')),
                ('nameOwner', models.CharField(max_length=100, verbose_name='name-owner')),
                ('addressOwner', models.CharField(max_length=100, verbose_name='address-owner')),
                ('emailOwner', models.CharField(max_length=100, verbose_name='email-owner')),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('idProperty', models.BigAutoField(primary_key=True, serialize=False)),
                ('addressProperty', models.CharField(max_length=100, unique=True, verbose_name='addressProperty')),
                ('typeProperty', models.IntegerField(verbose_name='type')),
                ('idOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='register.owner')),
            ],
        ),
    ]
